name: ci-cd
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/simple-java-maven-app

jobs:
  build-release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Bump version in pom.xml (uses Conventional Commits to pick major/minor/patch)
      - name: Bump Maven version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
        with:
          # optional:
          # pom-file: 'pom.xml'
          # version-path: '/project/version'
          # commit-message: 'Bump version'

      # Read the new version from pom.xml for tagging the image & release
      - name: Read project.version
        id: readver
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        with:
          tag_name: v${{ steps.readver.outputs.version }}
          release_name: v${{ steps.readver.outputs.version }}
          draft: false
          prerelease: false

      - name: Build JAR
        run: mvn -B -q -e package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.readver.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
