name: ci-cd

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/simple-java-maven-app

jobs:
  build-release-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # 1) Bump the PATCH version in pom.xml using an action
      - name: Increment pom version (patch)
        id: bump
        uses: christian-draeger/increment-pom-version@v1.9.0
        with:
          fromPom: "pom.xml"
          increment: "patch"

      - name: Commit bumped pom.xml
        uses: EndBug/add-and-commit@v9
        with:
          add: "pom.xml"
          message: "chore: bump version to ${{ steps.bump.outputs.newVersion }}"

      # 2) Create a semver tag that matches the pom version
      - name: Create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ steps.bump.outputs.newVersion }}
          tag_prefix: ""

      # 3) Create a GitHub Release from the new tag
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump.outputs.newVersion }}
          release_name: v${{ steps.bump.outputs.newVersion }}
          draft: false
          prerelease: false

      # 4) Build JAR
      - name: Build with Maven
        run: mvn -B -q -e package -DskipTests

      # 5) Build & push Docker
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.bump.outputs.newVersion }}
            ${{ env.IMAGE_NAME }}:latest
