name: ci-cd

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write     # commit, tag, release
  packages: write     # push GHCR images

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/simple-java-maven-app

jobs:
  build-release-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Bump version in pom.xml (Conventional-Commits; or swap to your preferred bump action)
      - name: Bump Maven version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
        # with:
        #   pom-file: 'pom.xml'
        #   version-path: '/project/version'

      # Read the exact bumped version so we can tag the release & image correctly
      - name: Read project.version
        id: readver
        run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Create Git tag (matches pom version)
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag "v${{ steps.readver.outputs.version }}" || true
          git push origin "v${{ steps.readver.outputs.version }}" || true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.readver.outputs.version }}
          release_name: v${{ steps.readver.outputs.version }}
          draft: false
          prerelease: false

      - name: Build JAR
        run: mvn -B -U -e -DskipTests -DskipITs -Dgpg.skip=true clean package

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.readver.outputs.version }}
            ${{ env.IMAGE_NAME }}:latest
